import { Montserrat } from 'next/font/google';
import '../globals.css';
import Header from '@/components/layout/header';
import MainSidebar from '@/components/layout/main-sidebar';

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
  fallback: ['sans-serif'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} flex flex-col min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
